// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDvWPIuVT6f3unukmu2dd4Z9NykhdE7o',
    appId: '1:39558485138:web:e6a58f38735281fb00424b',
    messagingSenderId: '39558485138',
    projectId: 'eirsfsm',
    authDomain: 'eirsfsm.firebaseapp.com',
    storageBucket: 'eirsfsm.firebasestorage.app',
    measurementId: 'G-NH6K10LSZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zCiAFQfwb3uXaXa2YWFlzs39bJfBzT4',
    appId: '1:39558485138:android:453526497bdbd08d00424b',
    messagingSenderId: '39558485138',
    projectId: 'eirsfsm',
    storageBucket: 'eirsfsm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfnNPG-lJksRzEu2JldjJBJXVgIYIu08',
    appId: '1:39558485138:ios:d31af97791e3c3af00424b',
    messagingSenderId: '39558485138',
    projectId: 'eirsfsm',
    storageBucket: 'eirsfsm.firebasestorage.app',
    iosBundleId: 'com.example.eirsFsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfnNPG-lJksRzEu2JldjJBJXVgIYIu08',
    appId: '1:39558485138:ios:d31af97791e3c3af00424b',
    messagingSenderId: '39558485138',
    projectId: 'eirsfsm',
    storageBucket: 'eirsfsm.firebasestorage.app',
    iosBundleId: 'com.example.eirsFsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHDvWPIuVT6f3unukmu2dd4Z9NykhdE7o',
    appId: '1:39558485138:web:bcb7c59254d5699d00424b',
    messagingSenderId: '39558485138',
    projectId: 'eirsfsm',
    authDomain: 'eirsfsm.firebaseapp.com',
    storageBucket: 'eirsfsm.firebasestorage.app',
    measurementId: 'G-7HCSXFEYDK',
  );
}
